version: '3'
services:
  frps:
    image: fatedier/frp:v0.63.0
    container_name: frps
    restart: always
    network_mode: host
    command: frps -c /etc/frp/frps.toml
    volumes:
      - ./frps.toml:/etc/frp/frps.toml
