SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
DEFAULT_RECIPIENT_SLACK="#monitoring"
SLACK_CHANNEL="#monitoring"
SLACK_USERNAME="netdata"
SLACK_ICON_URL="https://netdata.cloud/img/netdata.svg"

[slack]
enabled = yes


