SEND_SLACK="YES"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/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"
DEFAULT_RECIPIENT_SLACK="#monitoring"
SLACK_CHANNEL="#monitoring"
SLACK_USERNAME="netdata"
SLACK_ICON_URL="https://netdata.cloud/img/netdata.svg"

# 即使警报状态未变化，也要定期发送通知
SEND_CRITICAL_REPEAT_EVERY="30 60 120 180"
SEND_WARNING_REPEAT_EVERY="30 60 120"

# 防止警报频繁切换状态
ALARM_DONT_CLEAR_NOTIFICATION="YES"

[slack]
enabled = yes


