services:
  uv-ssh:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    container_name: uv-ssh
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '10022:22' # SSH端口
    volumes:
      - ./app:/app
      - /hdd16/uv_docker_cache:/root/.cache/uv
        # 挂载ZMQ socket文件
      - /tmp/zmq_data_test:/tmp/zmq_data_test
      - /hdd16/tmp/arrow_cache:/tmp/arrow_cache
      # 挂载R2中交易数据到/trade_data目录
      - /mnt/localB2fs/data:/trade_data:ro
      - /mnt/localB2fs/order-depth:/order-depth:ro
      - /mnt/localB2fs/depth-delta-a:/depth-delta-a:ro
      - /mnt/localB2fs/historical-orderbook:/historical-orderbook:ro
      - /mnt/localB2fs/merged-data/historical_orderbook:/merged-data:ro
    environment:
      - ROOT_PASSWORD=${ROOT_PASSWORD}
      # 从.env文件中读取Binance API密钥
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - DASHBOARD_URL=http://trade-dashboard-backend:3000
    working_dir: /app
    deploy:
      resources:
        limits:
          memory: 45G # 最大内存限制
    shm_size: 45G
    networks:
      - trade-network

networks:
  trade-network:
    driver: bridge
    external: true
