
services:
  jenkins:
    image: jenkins/jenkins:jdk17
    container_name: jenkins
    privileged: true
    user: "root"
    ports:
      - "8010:8080"
      - "50000:50000"
    environment:
      - http_proxy=http://172.88.0.1:7897
      - https_proxy=http://172.88.0.1:7897
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
    restart: unless-stopped
    networks:
      - vpn

networks:
  vpn:
    external: true