# 基础配置
bindAddr = "0.0.0.0"
bindPort = 5070

# Dashboard配置
webServer.addr = "0.0.0.0"
webServer.port = 5075
webServer.user = "admin"
webServer.password = "sean666_your_strong_password_here"

# 认证配置
auth.method = "token"
auth.token = "sean777_your_strong_token_here"

# 端口配置
transport.maxPoolCount = 10
allowPorts = [
    { start = 5700, end = 5710 }
]
