version: '3'

services:
  postgresql-slave:
    image: 'bitnami/postgresql:17.5.0'
    container_name: ${CONTAINER_NAME}
    restart: always
    user: root
    env_file: .env
    environment:
      - POSTGRESQL_REPLICATION_MODE=${POSTGRESQL_REPLICATION_MODE}
      - POSTGRESQL_MASTER_HOST=${POSTGRESQL_MASTER_HOST}
      - POSTGRESQL_MASTER_PORT_NUMBER=${POSTGRESQL_MASTER_PORT_NUMBER}
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - '${PORT}:5432'
    volumes:
      - './data:/bitnami/postgresql'

