version: '3'

services:
  postgresql-slave:
    image: 'xzsean/postgresql:18.2'
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file: .env
    user: root
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=${POSTGRESQL_MASTER_HOST}
      - POSTGRESQL_MASTER_PORT_NUMBER=${POSTGRESQL_MASTER_PORT_NUMBER}
      - POSTGRESQL_REPLICATION_USER=${POSTGRESQL_REPLICATION_USER}
      - POSTGRESQL_REPLICATION_PASSWORD=${POSTGRESQL_REPLICATION_PASSWORD}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - '${PORT}:5432'
    volumes:
      - './data:/bitnami/postgresql/data'
