# CPU 使用率告警
alarm: cpu_usage
on: system.cpu
lookup: average -3m percentage of user,system,softirq,irq,guest
units: %
every: 1m
warn: $this > 80
crit: $this > 90
info: CPU utilization is high
repeat: warning 10m critical 5m

# 内存使用率告警
alarm: ram_usage
on: system.ram
lookup: average -1m percentage of used
units: %
every: 1m
warn: $this > 80
crit: $this > 90
info: The percentage of RAM being used by the system.
repeat: warning 10m critical 5m

# 磁盘空间告
template: disk_full_percent
on: disk.space
units: %
calc: $used * 100 / ($avail + $used)
every: 1m
warn: $this > 80
crit: $this > 90
repeat: warning 10m critical 5m


# # 监控入站流量
# alarm: high_inbound_traffic
#     on: system.net
#     lookup: average -30s of received
#     units: kilobits/s
#     warn: $this > 100
#     crit: $this > 500
#     every: 30s
#     repeat: warning 1m critical 30s
#     info: "High inbound network traffic detected"
#     to: sysadmin

# # 监控出站流量
# alarm: high_outbound_traffic
#     on: system.net
#     lookup: average -30s of sent
#     units: kilobits/s
#     warn: $this > 100
#     crit: $this > 500
#     every: 30s
#     repeat: warning 1m critical 30s
#     info: "High outbound network traffic detected"
#     to: sysadmin

# 监控总网络流量
alarm: total_network_traffic
    on: system.net
    lookup: sum -30s of received,sent
    units: kilobits/s
    warn: $this > 200
    crit: $this > 1000
    every: 30s
    repeat: warning 1m critical 30s
    info: "High total network traffic detected (in+out)"
    to: sysadmin



