version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:17.5.0'
    container_name: postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres_password
      - POSTGRESQL_DATABASE=my_database
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
    ports:
      - '5432:5432'
    volumes:
      - 'data0:/bitnami/postgresql'
      
  postgresql-slave-1:
    image: 'bitnami/postgresql:17.5.0'
    container_name: postgresql-slave-1
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_PASSWORD=postgres_password
    ports:
      - '5433:5432'
    volumes:
      - 'data1:/bitnami/postgresql'

volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_1_data:
    driver: local

