version: '3'

services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      - ./app:/app
      - ./crontabs:/var/spool/cron/crontabs

    # ports:
    #   - "5060-5065:5060-5065"
    # environment:
    #   - http_proxy=http://127.0.0.1:7897
    #   - https_proxy=http://127.0.0.1:7897
    # -e HTTP_PROXY="http://myuser:mypassword@云服务器IP:13128" \
    # -e HTTPS_PROXY="http://myuser:mypassword@云服务器IP:13128" \

    user: 'root'
    network_mode: host
    restart: unless-stopped
    command: /usr/local/bin/start.sh

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
