version: '3'

services:
  app:
    container_name: ${PROJECT_NAME:-lst-service}
    build:
      context: .
      dockerfile: Dockerfile
      # 启用BuildKit缓存
      args:
        BUILDKIT_INLINE_CACHE: 1
    volumes:
      # 挂载整个项目目录
      - .:/app
      # 挂载日志目录
      - ./logs:/var/log
      - ./crontabs:/var/spool/cron/crontabs

    # ports:
    #   - "5060-5065:5060-5065"
    # environment:
    #   - http_proxy=http://127.0.0.1:7897
    #   - https_proxy=http://127.0.0.1:7897

    user: 'root'
    network_mode: host
    restart: unless-stopped
    command: /usr/local/bin/start.sh

    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'

    # 添加命令以便测试缓存
    # 可以通过 docker-compose run app sh 进入容器测试
    # command: tail -f /dev/null  # 保持容器运行用于调试
