serverAddr = "52.73.157.190"
serverPort = 5069
auth.token = "your_token_here"

{{- range $_, $v := parseNumberRangePair "5070-5080" "5070-5080" }}
[[proxies]]
name = "tcp-{{ $v.First }}"
type = "tcp"
localPort = {{ $v.First }}
remotePort = {{ $v.Second }}
{{- end }}