version: '3'

services:
  juicefs:
    image: juicedata/juicefs
    container_name: juicefs
    user: root
    volumes:
      - ${JFS_MOUNT_POINT}:/data
      - ./config:/root/.juicefs
      - ${JFS_CACHE_DIR}:/var/jfsCache
    env_file:
      - .env
    command: mount --cache-dir /var/jfsCache --cache-size ${JFS_CACHE_SIZE} /data
    privileged: true
    restart: unless-stopped
