[global]
    run as user = netdata

[web]
    web files owner = root
    web files group = root
    # 禁用身份验证
    enable = yes
    mode = static-threaded
    bind to = *
    auth = no

[plugins]
    proc = yes
    diskspace = yes
    cgroups = yes
    tc = yes
    idlejitter = yes
    enable running new plugins = yes
    check for new plugins every = 60
