version: '3'

services:
  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./crontabs:/var/spool/cron/crontabs

    # ports:
    #   - "5060-5065:5060-5065"
    # environment:
    #   - http_proxy=http://127.0.0.1:7897
    #   - https_proxy=http://127.0.0.1:7897

    user: "root"
    network_mode: host
    restart: unless-stopped
    command: sh -c "/app/startup.sh && cron && tail -f /var/log/cron.log"


